// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-b0e27H6UwHEiJSyo5r8pI9lYpO7mgFk',
    appId: '1:819122231420:web:b2b8590b08ae3b252491f9',
    messagingSenderId: '819122231420',
    projectId: 'revive75-bfce9',
    authDomain: 'revive75-bfce9.firebaseapp.com',
    storageBucket: 'revive75-bfce9.firebasestorage.app',
    measurementId: 'G-H8ZW2LJELD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAegRFMVyBwGcX7Y4TA6pxsXaZmP4daW6E',
    appId: '1:819122231420:android:c7d1da0fac7030c22491f9',
    messagingSenderId: '819122231420',
    projectId: 'revive75-bfce9',
    storageBucket: 'revive75-bfce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tiv2rbpNh_hb7pH0PNKglt78KybGdLo',
    appId: '1:819122231420:ios:091aa118d44bb7842491f9',
    messagingSenderId: '819122231420',
    projectId: 'revive75-bfce9',
    storageBucket: 'revive75-bfce9.firebasestorage.app',
    iosBundleId: 'com.example.revive75App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-tiv2rbpNh_hb7pH0PNKglt78KybGdLo',
    appId: '1:819122231420:ios:091aa118d44bb7842491f9',
    messagingSenderId: '819122231420',
    projectId: 'revive75-bfce9',
    storageBucket: 'revive75-bfce9.firebasestorage.app',
    iosBundleId: 'com.example.revive75App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-b0e27H6UwHEiJSyo5r8pI9lYpO7mgFk',
    appId: '1:819122231420:web:5afe65953f42b3602491f9',
    messagingSenderId: '819122231420',
    projectId: 'revive75-bfce9',
    authDomain: 'revive75-bfce9.firebaseapp.com',
    storageBucket: 'revive75-bfce9.firebasestorage.app',
    measurementId: 'G-Y443D1WKNY',
  );
}
